from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password
from django.utils import timezone
from datetime import date
import re

from .models import ClassTeacherAssignment
from classes.models import ClassStream
from subjects.models import ClassSubject

User = get_user_model()


class DateInput(forms.DateInput):
    input_type = 'date'


class StaffLoginForm(forms.Form):
    staff_no = forms.CharField(
        label="Staff No",
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Enter staff number"}),
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Enter password"}),
    )


class StaffUserCreationForm(UserCreationForm):
    """Form for creating new users - staff_id auto-generated"""

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'role', 'phone_number', 'address')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'role': forms.Select(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }


class StaffUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "is_staff", "is_superuser", "is_active")
        labels = {
            "username": "Staff No",
            "is_staff": "Active Staff Account",
            "is_superuser": "Administrator Access",
        }


class UserCreationForm(forms.ModelForm):
    """Form for superadmin to create new users. staff_id is auto-generated by the model."""
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        validators=[validate_password]
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Confirm Password"
    )

    # Teacher-specific fields
    qualification = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    specialization = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    hire_date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={
            'class': 'form-control',
            'type': 'date',
            # Restrict to past/present dates only (Issue #9)
            'max': date.today().isoformat(),
        })
    )

    class Meta:
        model = User
        # staff_id intentionally excluded — it is auto-generated in User.save() (Issue #1)
        fields = ['username', 'first_name', 'last_name', 'email', 'role', 'phone_number', 'address']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'role': forms.Select(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

    def clean_hire_date(self):
        """Ensure hire date is not in the future (Issue #9)."""
        hire_date = self.cleaned_data.get('hire_date')
        if hire_date and hire_date > date.today():
            raise forms.ValidationError("Hire date cannot be in the future.")
        return hire_date

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    """Form for superadmin to edit users. staff_id excluded — it must never change after creation (Issue #1)."""
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'role', 'phone_number', 'address', 'is_active']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'role': forms.Select(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class TeacherAssignmentForm(forms.Form):
    """Form for assigning class teacher (Issues #3 & #8)."""
    teacher = forms.ModelChoiceField(
        queryset=User.objects.filter(role='teacher'),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Teacher"
    )
    class_stream = forms.ModelChoiceField(
        queryset=ClassStream.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Class Stream"
    )
    academic_year = forms.CharField(
        max_length=9,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g., 2026/2027'}),
        label="Academic Year"
    )

    def clean_academic_year(self):
        """Validate academic year format and ensure it's current or future (Issue #3)."""
        academic_year = self.cleaned_data.get('academic_year', '').strip()

        if not re.match(r'^\d{4}/\d{4}$', academic_year):
            raise forms.ValidationError("Use the format YYYY/YYYY+1, e.g., 2026/2027.")

        start_str, end_str = academic_year.split('/')
        start_year, end_year = int(start_str), int(end_str)

        if end_year != start_year + 1:
            raise forms.ValidationError("Academic year must span consecutive years, e.g., 2026/2027.")

        current_year = date.today().year
        if start_year < current_year:
            raise forms.ValidationError(
                f"Academic year cannot be in the past. Use {current_year}/{current_year + 1} or later."
            )

        return academic_year

    def clean(self):
        """Prevent a teacher from being assigned to more than one class per year (Issue #8)."""
        cleaned_data = super().clean()
        teacher = cleaned_data.get('teacher')
        academic_year = cleaned_data.get('academic_year')

        if teacher and academic_year:
            existing = ClassTeacherAssignment.objects.filter(
                teacher=teacher,
                academic_year=academic_year,
                is_active=True,
            )
            if existing.exists():
                assigned_class = existing.first().class_stream.name
                raise forms.ValidationError(
                    f"{teacher.get_full_name() or teacher.username} is already the class teacher for "
                    f"'{assigned_class}' in {academic_year}. Each teacher can only hold ONE class per year."
                )

        return cleaned_data


class SubjectAssignmentForm(forms.Form):
    """Form for assigning subject teacher (Issue #3)."""
    teacher = forms.ModelChoiceField(
        queryset=User.objects.filter(role='teacher'),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Teacher"
    )
    class_subject = forms.ModelChoiceField(
        queryset=ClassSubject.objects.select_related('class_stream', 'subject'),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Class & Subject"
    )
    academic_year = forms.CharField(
        max_length=9,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g., 2026/2027'}),
        label="Academic Year"
    )

    def clean_academic_year(self):
        """Validate academic year format and ensure it's current or future (Issue #3)."""
        academic_year = self.cleaned_data.get('academic_year', '').strip()

        if not re.match(r'^\d{4}/\d{4}$', academic_year):
            raise forms.ValidationError("Use the format YYYY/YYYY+1, e.g., 2026/2027.")

        start_str, end_str = academic_year.split('/')
        start_year, end_year = int(start_str), int(end_str)

        if end_year != start_year + 1:
            raise forms.ValidationError("Academic year must span consecutive years, e.g., 2026/2027.")

        current_year = date.today().year
        if start_year < current_year:
            raise forms.ValidationError(
                f"Academic year cannot be in the past. Use {current_year}/{current_year + 1} or later."
            )

        return academic_year