# Generated by Django 5.2.15 on 2026-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_no",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
