# Generated by Django 5.2.15 on 2026-06-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradescale",
            options={
                "ordering": ["-max_mark"],
                "verbose_name": "Grade Scale",
                "verbose_name_plural": "Grade Scales",
            },
        ),
        migrations.AlterField(
            model_name="gradescale",
            name="grade",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B", "B"),
                    ("B-", "B-"),
                    ("C+", "C+"),
                    ("C", "C"),
                    ("C-", "C-"),
                    ("D+", "D+"),
                    ("D", "D"),
                    ("D-", "D-"),
                    ("E", "E"),
                ],
                max_length=2,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="gradescale",
            name="max_mark",
            field=models.PositiveSmallIntegerField(verbose_name="Maximum Mark"),
        ),
        migrations.AlterField(
            model_name="gradescale",
            name="min_mark",
            field=models.PositiveSmallIntegerField(verbose_name="Minimum Mark"),
        ),
    ]
