# Generated by Django 4.2.29 on 2026-06-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_default_grade_scales"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradescale",
            options={"ordering": ("min_mark",)},
        ),
        migrations.AlterField(
            model_name="gradescale",
            name="grade",
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
