# Generated by Django 6.0.6 on 2026-06-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_alter_gradescale_options_alter_gradescale_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="term",
            field=models.CharField(
                choices=[("1", "Term 1"), ("2", "Term 2"), ("3", "Term 3")],
                max_length=1,
            ),
        ),
    ]
