from django import forms
from .models import Student


class StudentForm(forms.ModelForm):
    """
    Student creation/edit form.
    admission_no is intentionally excluded — it is auto-generated by Student.save() (Issue #2).
    """
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'class_stream']

        help_texts = {
            'first_name': "Enter student's first name (e.g. John)",
            'last_name': "Enter student's last name (e.g. Kamau)",
            'class_stream': "Select class like 'Form 1A', 'Form 2B', etc."
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'id': 'id_first_name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'id': 'id_last_name'}),
            'class_stream': forms.Select(attrs={'class': 'form-control', 'id': 'id_class_stream'}),
        }

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if not first_name:
            raise forms.ValidationError("First name is required.")

        first_name = first_name.strip().title()

        if len(first_name) < 2:
            raise forms.ValidationError("First name is too short.")

        if not first_name.isalpha():
            raise forms.ValidationError("First name must contain only letters.")

        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')

        if not last_name:
            raise forms.ValidationError("Last name is required.")

        last_name = last_name.strip().title()

        if len(last_name) < 2:
            raise forms.ValidationError("Last name is too short.")

        if not last_name.isalpha():
            raise forms.ValidationError("Last name must contain only letters.")

        return last_name